apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
# Master
- role: control-plane
# Worker
- role: worker
  extraPortMappings:
  - containerPort: 5900
    hostPort: 5900
    listenAddress: "0.0.0.0"