---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-hpa
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: php-apache
 namespace: demo-hpa
spec:
 selector:
   matchLabels:
     run: php-apache
 replicas: 1
 template:
   metadata:
     labels:
       run: php-apache
   spec:
     containers:
     - name: php-apache
       image: k8s.gcr.io/hpa-example
       ports:
       - containerPort: 80
       resources:
         limits:
           cpu: 100m
         requests:
           cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
 name: php-apache
 namespace: demo-hpa
 labels:
   run: php-apache
spec:
 ports:
 - port: 80
 selector:
   run: php-apache
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache-hpa
  namespace: demo-hpa
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache