---
apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: demo-hpa
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while sleep 0.01; do wget -q -O- http://php-apache; done
    image: busybox
    imagePullPolicy: Always
    name: load-generator
