---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-version
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-version
  name: demo-version
  namespace: demo-version
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-version
  template:
    metadata:
      labels:
        app: demo-version
    spec:
      containers:
      - image: tourna/demo:v1
        imagePullPolicy: Always
        name: demo-version
        ports:
        - containerPort: 8080
          name: http
---
kind: Service
apiVersion: v1
metadata:
  name: demo-version-service
  namespace: demo-version
spec:
  selector:
    app: demo-version
  ports:
  # Default port used by the image
  - port: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-version-certs
  namespace: demo-version
type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-version-ingress
  namespace: demo-version
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
  - hosts:
      - localhost
    secretName: demo-version-certs
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: /demo(/|$)(.*)
        backend:
          service:
            name: demo-version-service
            port:
              number: 8080